import React from "react"
import SideNav from './components/sidenav'
import Navbar  from "./components/navbar"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="flex">
        <SideNav/>
        <main className="flex-1">
        <Navbar/>
        {children}
        </main>
        </div>
        </body>
    </html>
  )
}

